devops_user: "devops"
devops_group: "devops"
devops_shell: "/bin/bash"

ntp_servers:
  - "pool.ntp.org"
  - "time.google.com"

allowed_tcp_ports:
  - 22
  - 80
  - 443
  
extra_users:
  - name: "appuser"
    shell: "/bin/bash"
  - name: "auditor"
    shell: "/bin/bash"

deploy_dir: "/opt/labapp"
