$ANSIBLE_VAULT;1.1;AES256
61386634633365303133363766323038383230323630343438333966313136633962626437616431
3031636561313061636565363132656231396437616530660a333763643032633535303438636234
34613931346635393938646537326135396134353263623531663631373461653735363134656662
3062353338636662390a316131646563623938393439346539303837643435333666326262306533
61653665346433613765303731373665353535643434373238643839353763366134656635373765
33323134326535626232393065323131623338326336643861313433613864386565363534313833
66663439306538353466336135316237656361633765313564303739396138333532363363613562
61393938663337663433346465643963326164363561303866663665616330356462633839386233
32316233616238303964313338633935343337323934656334353430353365343137323433306435
6536646330303533633033363764653865373639376434343063
